services:
  - type: web
    name: cloud-study-document-manager
    runtime: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
